import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SiWhatsapp } from "react-icons/si";
import Link from "next/link";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Navbar />
        {children}
        <div className="bg-colorGreen inline-block rounded-full text-colorWhite fixed bottom-8 right-8 p-2">
          <Link target="_blank" href="https://wa.me/5521991348429"><SiWhatsapp size={30}  /></Link>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
